Repository schnappi21/discord-giveaway-bot, pull requests merged in 2021-05, with the labels that each got.

#65 add parseInt()
  commands/start.js
Labels: bug

#68 re-update message.js
  events/message.js
Labels: enhancement

#66 maybe give me full access?!?!
  README.md
Labels: documentation

#71 V2.2.0?
  README.md
  commands/Giveaways/end.js
  commands/Giveaways/reroll.js
  commands/Giveaways/start.js
  commands/Main/help.js
  commands/end.js
  commands/help.js
  commands/reroll.js
  commands/start.js
  config.json
  events/client/ready.js
  events/guild/message.js
  events/message.js
  events/ready.js
  handlers/command.js
  handlers/event.js
  index.js
  package-lock.json
  package.json
  setup.bat
  start.bat
Labels: dependencies, documentation, enhancement

#73 Add new options in config.json (#72)
  README.md
  commands/Giveaways/start.js
  config.json
Labels: documentation, enhancement
