Repository schnappi21/discord-giveaway-bot, pull requests merged in 2021-04, with the labels that each got.

#40 ✏️ Updated links & names
  README.md
  commands/help.js
  package.json
Labels: documentation

#43 V2.0.1
  package-lock.json
  package.json
  start.bat
Labels: documentation

#45 V2.0.2
  commands/end.js
  commands/reroll.js
  commands/start.js
  index.js
Labels: documentation

#46 V2.0.3
  README.md
  commands/help.js
Labels: documentation

#44 ✏️ 🎨 Fixed spelling, added markdown
  commands/end.js
  commands/reroll.js
  commands/start.js
Labels: documentation

#47 change prize to giveawayPrize
  commands/start.js
Labels: bug

#48 V2.0.4
  README.md
  commands/start.js
Labels: bug, documentation

#50 V2.1.0
  package-lock.json
  package.json
Labels: documentation

#56 Little spelling error
  README.md
Labels: documentation

#55 ⚙️ Added setup.bat file
  setup.bat
Labels: enhancement
